version: "2.0"

services:
  sunshine:
    image: {{sunshineImage}}
    expose:
      - port: 47984
        as: 47984
        to:
          - global: true
      - port: 47989
        as: 47989
        to:
          - global: true
      - port: 47990
        as: 47990
        to:
          - global: true
      - port: 48010
        as: 48010
        to:
          - global: true
      - port: 47998
        as: 47998
        proto: udp
        to:
          - global: true
      - port: 47999
        as: 47999
        proto: udp
        to:
          - global: true
      - port: 48000
        as: 48000
        proto: udp
        to:
          - global: true
      - port: 48002
        as: 48002
        proto: udp
        to:
          - global: true
      - port: 48010
        as: 48010
        proto: udp
        to:
          - global: true
    endpoints:
      sunshine-ip:
        kind: ip

profiles:
  compute:
    sunshine:
      resources:
        cpu:
          units: {{cpuUnits}}
        memory:
          size: {{memoryGb}}
        storage:
          - size: 128Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: {{gpuModel}}
                  ram: {{gpuRam}}
                  interface: pcie

  placement:
    akash:
      attributes:
        feat-endpoint-ip: true
      pricing:
        sunshine:
          denom: uakt
          amount: {{maxUaktPerBlock}}
        sunshine-ip:
          denom: uakt
          amount: {{ipLeaseUaktPerBlock}}

deployment:
  sunshine:
    akash:
      profile: sunshine
      count: 1
