version: "2.0"
services:
  sunshine:
    image: {{sunshineImage}}
    expose:
      - { port: 3000, as: 3000, proto: tcp, to: [{ global: true }] }
      - { port: 3001, as: 3001, proto: tcp, to: [{ global: true }] }
profiles:
  compute:
    sunshine:
      resources:
        cpu: { units: {{cpuUnits}} }
        memory: { size: {{memoryGb}} }
        storage: [{ size: 64Gi }]
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx3090
                - model: rtx4090
                - model: rtx4070
                - model: rtx3080
                - model: rtx3070
                - model: a10
                - model: a40
  placement:
    akash:
      pricing:
        sunshine: { denom: uact, amount: {{maxUaktPerBlock}} }
deployment:
  sunshine:
    akash: { profile: sunshine, count: 1 }
